spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:hw14
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      port: 27017
      database: hw14

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{35} - %msg%n"
  level:
    root: info