spring:
  datasource:
#    driver-class-name: 'org.postgresql.Driver'
#    url: 'jdbc:postgresql://postgres:5432/db'
#    username: 'postgres'
#    password: 'postgres'
    #initialization-mode: always
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,logfile"
  endpoint:
    health:
      enabled: true
      show-details: always

logging:
  file:
    name: hw17.log
  level:
    root: debug
    org.springframework.web: debug
    org.hibernate: error


