spring:
  datasource:
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:mem:hw12
    username: sa
  jpa:
    #generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#  thymeleaf:
#    prefix:
#      classpath: /templates/
#    suffix: .html

